spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    thymeleaf:
      enabled: true
      prefix: classpath:/templates/
      suffix: .html
      cache: false
